 export const CREATE_ORDER_REQUEST ="CREATE_ORDER_REQUEST";
 export const CREATE_ORDER_SUCCESS ="CREATE_ORDER_SUCCESS";
 export const CREATE_ORDER_FAIL ="CREATE_ORDER_FAIL";

 export const LIST_ORDER_REQUEST ="LIST_ORDER_REQUEST";
 export const LIST_ORDER_SUCCESS ="LIST_ORDER_SUCCESS";
 export const LIST_ORDER_FAIL ="LIST_ORDER_FAIL";

 export const DELETE_ORDER_REQUEST ="DELETE_ORDER_REQUEST";
 export const DELETE_ORDER_SUCCESS ="DELETE_ORDER_SUCCESS";
 export const DELETE_ORDER_FAIL ="DELETE_ORDER_FAIL";

 export const UPDATE_ORDER_REQUEST ="UPDATE_ORDER_REQUEST";
 export const UPDATE_ORDER_SUCCESS ="UPDATE_ORDER_SUCCESS";
 export const UPDATE_ORDER_FAIL ="UPDATE_ORDER_FAIL";

 export const LIST_MY_ORDER_REQUEST ="LIST_MY_ORDER_REQUEST";
 export const LIST_MY_ORDER_SUCCESS ="LIST_MY_ORDER_SUCCESS";
 export const LIST_MY_ORDER_FAIL ="LIST_MY_ORDER_FAIL";

 export const SAVE_UPLOAD_REQUEST="SAVE_UPLOAD_REQUEST";
 export const SAVE_UPLOAD_SUCCESS="SAVE_UPLOAD_SUCCESS";
 export const SAVE_UPLOAD_FAIL="SAVE_UPLOAD_FAIL";