export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST";
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS";
export const PRODUCT_LIST_FAIL = "PRODUCT_LIST_FAIL";

export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST";
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS";
export const PRODUCT_DETAILS_FAIL = "PRODUCT_DETAILS_FAIL";

export const TYPE_TRAIN_REQUEST = "TYPE_TRAIN_REQUEST";
export const TYPE_TRAIN_SUCCESS = "TYPE_TRAIN_SUCCESS";
export const TYPE_TRAIN_FAIL = "TYPE_TRAIN_FAIL";

export const TYPE_TRAIN_LIST_REQUEST = "TYPE_TRAIN_LIST_REQUEST";
export const TYPE_TRAIN_LIST_SUCCESS = "TYPE_TRAIN_LIST_SUCCESS";
export const TYPE_TRAIN_LIST_FAIL = "TYPE_TRAIN_LIST_FAIL";

export const ADD_PRODUCT_REQUEST = "ADD_PRODUCT_REQUEST";
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";
export const ADD_PRODUCT_FAIL = "ADD_PRODUCT_FAIL";

export const SEARCH_PRODUCT_REQUEST = "SEARCH_PRODUCT_REQUEST";
export const SEARCH_PRODUCT_SUCCESS = "SEARCH_PRODUCT_SUCCESS";
export const SEARCH_PRODUCT_FAIL = "SEARCH_PRODUCT_FAIL";